// <auto-generated />
namespace UNASP.MBarber.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImagemEmpresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImagemEmpresa));
        
        string IMigrationMetadata.Id
        {
            get { return "201805232013245_ImagemEmpresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
