// <auto-generated />
namespace UNASP.MBarber.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTipoServico : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTipoServico));
        
        string IMigrationMetadata.Id
        {
            get { return "201805171737599_AddTipoServico"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
