//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNASP.MBarber.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliaco
    {
        public int Id { get; set; }
        public string Nota { get; set; }
        public string Descricao { get; set; }
        public int ServicoId { get; set; }
    
        public virtual Servico Servico { get; set; }
    }
}
