//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNASP.MBarber.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public System.Guid Id { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Agendamento Agendamento { get; set; }
        public virtual Avaliacao Avaliacao { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
